Bhavya1352/eventmappr

- index.html
- style.css
This PR improves the **UI/UX of the header and form controls** section for better usability and visual consistency.
-  **Aligned** all header and form elements centrally  
-  **Styled** `input`, `select`, and `button` to have consistent border-radius, padding, and hover effects  
-  **Added responsiveness** using Flexbox with proper wrapping  
-  Improved visual contrast added bootstrap buttons 
Closes: #4
> UI improvement: Header layout and form styling

- script.js
- style.css
Fixes: #7 
- [✔️] Bug Fix 🐛
- [✔️] New Feature ✨
- [❌] Documentation 📚
- [✔️] UI/UX Enhancement 🎨
- [❌] Refactor 🧹
- [✔️] My code follows the contribution guidelines of eventmappr
- [✔️] I have tested my changes locally
- [❌] I have updated relevant documentation
- [❌] I have linked related issues (if any)
- [✔️] This pull request is ready to be reviewed
**### 👀❌before**
https://github.com/user-attachments/assets/998eea33-d13c-41a8-a4ba-838ee9b4173f
**### 👀✔️after**
https://github.com/user-attachments/assets/82658cd6-19f0-4e1e-ab55-eec2f434cc21
Thank you for reviewing this pull request!  
Looking forward to your valuable feedback and suggestions to improve this further.  
Together, let’s build a cleaner and more delightful …
> added feature of alert with popup with demo videos

- animations.js
- event-details.html
- event-details.js
- index.html
- style.css
This PR introduces smooth entrance, scroll-triggered, and hover animations using GSAP to enhance the user experience across key pages.
Fixes: #40
Changes Made->
- Implemented page load animations for headers, controls, maps, and footers.
- Added smooth transitions when event details content loads.
- Introduced scroll-based animations to reveal information dynamically as the user scrolls.
- Enhanced hover interactions on buttons, gallery items, and modal navigation.
- Applied modal open/close animations for better visual flow.
- Ensured animations are smooth, non-blocking, and visually consistent.
https://github.com/user-attachments/assets/292e0466-6ad8-4c93-b879-3bcb0458a164
> FIX #40: Added smooth GSAP animations and interactive UI effects

- event-details.html
- node_modules/.bin/atob
- node_modules/.bin/atob.cmd
- node_modules/.bin/atob.ps1
- node_modules/.bin/live-server
- node_modules/.bin/live-server.cmd
- node_modules/.bin/live-server.ps1
- node_modules/.bin/uuid
- node_modules/.bin/uuid.cmd
- node_modules/.bin/uuid.ps1
This PR fixes the issue where the event description icon was misaligned and not properly indented in the UI. The icon now aligns correctly with the text, improving the visual hierarchy and accessibility.
> event description icon was misaligned and not properly indented in the UI

- index.html
This PR integrates a full LLM-based chatbot into EventMappr, enabling it to answer users' queries effectively. The chatbot can handle both general inquiries and questions specifically related to EventMappr, such as event discovery, filtering, and usage guidance. The integration leverages Botpress to provide a seamless user experience.
Additionally, the feedback button has been relocated to the bottom center of the page. Previously, it was occupying the bottom-right corner, which conflicted with the chatbot button's position and caused confusion. This adjustment resolves the placement conflict and ensures a better user interface.
Fixes: #85
- [✓] Bug Fix 🐛
- [✓] New Feature ✨
- [✓] Documentation 📚
- [✓] UI/UX Enhancement 🎨
- [✓] Refactor 🧹
- [✓] My code follows the contribution guidelines …
> feat: Add chatbot integration using Botpress (#85) #resolvedPR

- faq.css
- index.html
I added a frequently added questions sections with some basic questions a first time user might have while using the website.
*note: i've also added my faq section in the navbar and enabled the scroll to section for the same*
Fixes: #75 
- [✅ ] New Feature ✨
- [✅ ] My code follows the contribution guidelines of Civix
- [✅ ] I have tested my changes locally
- [✅ ] I have updated relevant documentation
- [✅ ] I have linked related issues (if any)
- [ ✅] This pull request is ready to be reviewed
Could you review my pull request.
Thank you!
> Added FAQ section

- index.html
- scroll-to-top.js
- style.css
Adds Scroll to top button
Fixes: #117 
-[x] I have linked related issues (if any)
https://github.com/user-attachments/assets/1d569b68-362b-4b77-80b0-3c58a72b2a1e
> Added Scroll-to-top Button Issue #117

- explore.html
- script.js
- style.css
Hi! This is pull request with respect to Issue #124  for adding dark theme across website for better user experience.
I'm adding a demo video.
https://github.com/user-attachments/assets/611bf6ed-7de5-4743-b8f0-ba2a9209682b
> Dark mode added

- index.html
Map anchor tag fixed. 
Issue: #123 
Now it redirects to explore.html
> bug-fixed- map anchor tag

- index.html
Two words are commented out in the code for the better readability of the developer
-main (line 151)
-create-contact-us (line 188)
in index.html
Fixes: #149 
Please check @Bhavya1352 and merge the PR
> commented the words

- components/sections/FAQSection.js
modified the contact us button like the sign in button style
Fixes: #169 
Please @Bhavya1352 @HarshS16 check and merge the PR
> modified the cotact us button

- components/sections/ContactSection.js
- package-lock.json
I have added a small section in which a map shows office location in contact page. I have tested map section is responsive
Fixes: #175
- [✅ ] New Feature ✨
- [ ✅] UI/UX Enhancement 🎨
- [✅ ] My code follows the contribution guidelines of Civix
- [✅ ] I have tested my changes locally
- [✅ ] This pull request is ready to be reviewed
> FIX #175: Addition of map which shows office location

- pages/tourist-places.js
- src/App.js
- src/components/layout/Navbar.js
- src/components/sections/TouristPlacesMap.js
- src/components/sections/TouristPlacesSection.js
- src/pages/tourist-places.js
- src/styles/AppStyles.css
- utils/routes.js
This PR introduces a powerful and user-friendly **Tourist Attractions Finder** to Eventmappr, enabling users to instantly discover historical and cultural places of interest near their current location.
By leveraging the browser’s Geolocation API and the Overpass API, users can find attractions such as museums, monuments, landmarks, and viewpoints within a 5km radius. The results are presented on an interactive, modern map interface, with a visually appealing sidebar for quick browsing.
---
- 🌍 **Live Location Detection:** Seamlessly detects the user's current position using the browser’s Geolocation API.
- 🏛️ **Rich Place Data:** Fetches a curated list of historical and tourist attractions (museums, monuments, landmarks, viewpoints, etc.) via Overpass API.
- 🗺️ **Interactive Map:** …
> Add tourist attractions finder using geolocation

- components/layout/Navbar.js
- components/map/MapExplorer.js
- components/map/NearbyPlaces.js
- components/map/NearbyPlacesPanel.js
- package-lock.json
- pages/nearby.js
Fixes : #162 
This PR adds a dedicated Nearby page to Eventmappr, allowing users to easily find restaurants and hotels near their current location.
**Key features:**
- New `/nearby` page listing nearby restaurants and hotels using the OpenStreetMap Overpass API.
- “Nearby” link added to the navbar for quick access.
- Improved text visibility for both light and dark themes.
- Each place includes a “Get Location” button that opens Google Maps at the exact coordinates.
- Increased search radius to 3km for more comprehensive results.
[Feature]:🚀Add “Nearby Restaurants & Hotels” Feature #162
https://github.com/user-attachments/assets/55c4e0db-08ca-4dba-9672-0cc7a7420c80
> Add Nearby page for restaurants & hotels

- components/layout/Navbar.js
- package-lock.json
- pages/currency-converter.js
🚀 Added a **Currency Converter Widget** to help international users convert currencies directly within Eventmappr, especially while planning for events with price details in different currencies.
Fixes: #163
Here’s how the Currency Converter Widget looks inside the app:
https://github.com/user-attachments/assets/46b45d57-772f-42df-b3f8-78cd27ced607
---
🙋‍♀️ Review Requested:  
@HarshS16 @Bhavya1352
Looking forward to your feedback!
> 🚀 Added Currency Converter Widget

- components/sections/ContactSection.js
- package-lock.json
- package.json
- pages/contact.js
- styles/globals.css
Enhanced contact page: improved hero section layout, fixed dark mode persistence, updated GIF handling, and ensured all UI elements are visible and professional in both light and dark modes. Also addressed animation and theme toggle reliability.
Fixes: #201 
https://github.com/user-attachments/assets/b9efade6-1876-4043-b786-36e3f79d6e30
> 🚀 Enhanced contact page

- components/sections/HeroSection.js
This PR introduces a dynamic typing effect for the "Discover Events on Map" text in the Hero section, enhancing the visual appeal and interactivity of the landing page.
Fixes: #215 
https://github.com/user-attachments/assets/1277f280-ee4f-4ce5-b13e-cb666f56a292
> ✨ Pull Request: Add Typing Effect for "Discover Events on Map" in Hero Section

- components/Cursor.jsx
- components/sections/FAQSection.js
- pages/_app.js
Fixes: #217 
This PR introduces a custom-styled pointer cursor component ([Cursor.jsx](cci:7://file:///c:/Users/Akshitha/Downloads/msme/eventmappr/components/Cursor.jsx:0:0-0:0)) to enhance the visual interactivity and modern feel of the EventMappr UI. The cursor features a vibrant, animated triangle design and smooth hover/click effects, replacing the default system pointer for desktop users. The integration is responsive and automatically falls back to the default cursor on mobile devices.
- Adds [components/Cursor.jsx](cci:7://file:///c:/Users/Akshitha/Downloads/msme/eventmappr/components/Cursor.jsx:0:0-0:0) with all logic and styles encapsulated.
- Integrates the custom cursor into the main app layout via [_app.js](cci:7://file:///c:/Users/Akshitha/Downloads/msme/eventmappr/pages/_app. …
> ✨ Feature Request: Add Custom-Styled Pointer Cursor for Enhanced UI Experience

- components/sections/HeroSection.js
- Improved visibility of `.event-title` in dark theme by using proper color contrast.
- Updated `.event-details` text color to red for better visibility and emphasis.
- Ensured card background works well in both light and dark themes.
Fixes: #225 
- [/ ] UI/UX Enhancement 🎨
- [/ ] My code follows the contribution guidelines of Civix
- [/ ] I have tested my changes locally
- [/ ] I have updated relevant documentation
- [/ ] I have linked related issues (if any)
- [/ ] This pull request is ready to be reviewed
> ENHANCE: Improve event card visibility and update time text color

- .env.example
- components/ChatBot.js
- package-lock.json
This PR integrates Gemini 1.5 Flash into the EventMappr chatbot for smarter and more contextual replies. Instead of hardcoded responses, the assistant now leverages Gemini to answer user queries based on platform-specific context.
Fixes: #234 
New Feature ✨
-  Gemini response logic added with fallback for API issues
-  EventMappr context prompt crafted for accurate replies
-  UI/UX left unchanged and all current animations preserved
-  Tested locally – working as expected
-  Issue raised & assigned under GSSoC'25
**⚠️ Note:** Please ensure you set NEXT_PUBLIC_GEMINI_API_KEY in Vercel environment variables before merging and redeploying, otherwise the assistant will fall back to default responses.
Old Chatbot 
New LLM-Powered Chatbot
It can even neglect typos by the users like I used here …
> Enchanced chatbot response system

- components/layout/Navbar.js
- package-lock.json
This PR addresses two key UI issues in the Eventmappr navbar:
1.  Fixes the duplicate logo issue — previously, two logos were showing up on the navbar due to improper markup or CSS layout. This has now been resolved to display only one logo cleanly.
2. Resolves logo and nav item overlap — ensured the logo and navigation items no longer clash on smaller screens or specific layouts.
Fixes: #241 
bug img: <img width="1917" height="104" alt="Screenshot 2025-07-23 182406" src="https://github.com/user-attachments/assets/acaae9d7-4c48-4c88-8ba7-7c30afe63a0b" />
to 
fixed img :
> fix the overllaping of logo and nav-items in navbar and add some gaps in nav items

- pages/currency-converter.js
📌 Summary #271 
This PR aligns the Currency Converter page with the overall design system and visual language of the application. The previous design was inconsistent in terms of typography, spacing, and theming. This update ensures visual cohesion across all screens, including Login, Register, and Dashboard.
✅ What’s Improved
Typography: Updated all text to use GoogleFonts.nunito to match the app’s standard.
Color Scheme: Integrated the global light/dark theme system.
Buttons & Inputs:
Matching shape, padding, and shadows
Smooth hover and focus transitions
Layout:
Aligned spacing with app-wide layout rules
Centered content using flex or grid
Hover Effects: Added elegant transform and box-shadow animations for interactive elements …
> UI Revamp for Currency Converter Page

- components/layout/Navbar.js
- components/map/NearbyPlaces.js
- components/map/NearbyPlacesPanel.js
- pages/nearby.js
✅ Description
Fixed critical UI/UX bugs affecting navbar spacing, modal positioning, and layout consistency across the application. Resolved issues with navbar margin/padding, modal z-index causing footer displacement, and container structure problems in nearby places section.
Fixes: #268
📂 Type of Change
Bug Fix 🐛
UI/UX Enhancement 🎨
📋 Checklist
My code follows the contribution guidelines of Eventmappr
I have tested my changes locally
I have updated relevant documentation
I have linked related issues (if any)
This pull request is ready to be reviewed
🎥 Screenshots
Fixed navbar spacing with consistent padding system
Modal overlay no longer interferes with footer positioning
Nearby places page maintains proper layout during location detection
Enhanced responsive design across all screen …
> [Bug]: Fix Navbar Spacing and Layout Issues in Nearby Places Section #268

- components/layout/Navbar.js
I have fixed the sign in button using whitespace : nowrap in navbar.js
Fixes: #270
> Fixed sign in button

- components/Cursor.jsx
- package-lock.json
- package.json
- pages/currency-converter.js
📦 **Pull Request: Eventmappr - Currency Converter UI Revamp**
This PR revamps the **Travel Currency Converter** page for Eventmappr, focusing on a modern, dynamic UI.
**Key updates:**
- Redesigned layout matching Eventmappr’s theme.
- Dynamic 7-day currency trend chart (auto-refresh every 5 seconds).
- Horizontal **Amount / From / To** fields for better alignment.
- Credit-card-style conversion result card instead of plain text.
- Background image & semi-transparent card for a travel-themed aesthetic.
- Fixed alignment, responsiveness, and enhanced visual hierarchy.
**Fixes:** #274 (UI improvement for currency converter)
---
---
---
---
@Bhavya1352 **Could you please authorize the Vercel deployment?**  
The build works locally and is ready to merge once deployment is approved.
> Currency UI

- src/styles/Home.css
Enhanced the navbar with a modern **glassy sticky effect** using `backdrop-filter`, updated border radius, and smoother box shadows for an elegant UI.
Fixes: #269
> Added the glassy navbar

- components/sections/FAQSection.js
This PR solves the UI problem of FAQ.
Fixes: #295 
- [ /] UI/UX Enhancement 🎨
- [ /] My code follows the contribution guidelines of Eventmappr
- [ /] I have tested my changes locally
- [ /] I have updated relevant documentation
- [ /] I have linked related issues (if any)
- [ /] This pull request is ready to be reviewed
https://github.com/user-attachments/assets/651a5c40-1fbb-41af-84c6-ca4d5243651b
>  ENHANCE: change  the UI of  faq

- README.md
Fixes: #255 
- [ Yes] Documentation 📚
- [ Yes] My code follows the contribution guidelines of Eventmappr
- [Yes ] I have tested my changes locally
- [ Yes] I have updated relevant documentation
- [ Yes] I have linked related issues (if any)
- [Yes ] This pull request is ready to be reviewed
> added a top arrow in a readme.md

- package-lock.json
- src/components/sections/TouristPlacesSection.js
> Changed the colour of place title to make it more visible

- pages/currency-converter.js
Enhanced UI of Currency Conversion  Page.
Fixes: https://github.com/Bhavya1352/eventmappr/issues/321
> Improved UI of Currency Convertor

- pages/cookies.jsx
- pages/privacy.jsx
- pages/terms.jsx
Enhancement of the UI of Cookies Page, Privacy Page & Terms Page.
Fixes: https://github.com/Bhavya1352/eventmappr/issues/329
https://github.com/user-attachments/assets/027f24a9-3dbb-4d78-bf5e-c676f08b01cf
https://github.com/user-attachments/assets/26bf5fe9-645f-46eb-9c3c-8ed89c5f6ce1
https://github.com/user-attachments/assets/c5e8ba91-63a8-48f0-8b10-cd915be701f4
> Improved UI of Cookies, Terms & Privacy

- pages/nearby.js
Near By page has now improved UI.
Fixes: https://github.com/Bhavya1352/eventmappr/issues/335
https://github.com/user-attachments/assets/f6bfd2d3-5f45-4309-9e94-1208dd94258b
> Improved UI of Near By Page

- components/Cursor.jsx
- styles/globals.css
change color of cursor
Fixes: #340
- [x ] UI/UX Enhancement 🎨
- [x ] My code follows the contribution guidelines of Eventmappr
- [x ] I have tested my changes locally
- [x ] I have updated relevant documentation
- [x ] I have linked related issues (if any)
- [x ] This pull request is ready to be reviewed
@Bhavya1352
> Cursorcolor resolves issue#340

- src/components/sections/TouristPlacesSection.js
Improved UI of Tourist Places.
Fixes: https://github.com/Bhavya1352/eventmappr/issues/349
> Improved UI of Tourist Places

- pages/about.js
About Page now have Modern UI.
Fixes: https://github.com/Bhavya1352/eventmappr/issues/359
> Improved UI of About Page

- components/layout/Navbar.js
- src/styles/Weather.css
- styles/globals.css
This PR fixes the navbar logo issue where the logo was either not visible or misaligned in the navigation bar.
The update ensures that the logo:
Loads correctly in all environments.
Maintains proper alignment with the navbar items.
Scales and remains responsive across different screen sizes and devices.
Changes made:
Fixed the src path and ensured the correct file reference for the logo image.
Adjusted CSS styling in globals.css to align the logo properly.
Updated Navbar.js layout to ensure responsive logo display.
✅ Bug Fix 🐛
New Feature ✨
Documentation 📚
UI/UX Enhancement 🎨
Refactor 🧹
Other:
My code follows the contribution guidelines of Eventmappr
✅ I have tested my changes locally
✅ I have updated relevant documentation (if applicable)
✅ I have linked related issues (if any)
✅ This …
> fix: resolve navbar logo issue

- components/map/MapExplorer.js
Reverts Bhavya1352/eventmappr#373
Causing vercel deployment errors
> Revert "FEATURE : add event btn"

- components/map/MapExplorer.js
- components/map/NearbyPlaces.js
Added custom Leaflet icons for different types of places since there was already the map implementation done,
Restaurants, Cafes, Fast Food → Red restaurant icon (flaticon)
Hotels & Guest Houses → Hotel icon
Other places → Default location pin
Implemented a getPlaceIcon() function to dynamically assign icons based on OSM tags.
Updated <Marker /> components to use the correct custom icons instead of the default Leaflet blue pin.
Benefits
Provides a more intuitive and user-friendly map experience.
Users can easily distinguish between restaurants, hotels, and general points of interest.
Maintains flexibility to extend icons for more categories (bars, pubs, etc.).
Fixes: #366
> issue #366 add map view for event location

- components/map/MapExplorer.js
- components/map/NearbyPlaces.js
Reverts Bhavya1352/eventmappr#412
> Revert "issue #366 add map view for event location"

- components/Cursor.jsx
This PR improves the cursor visibility in both light and dark modes by ensuring proper contrast.
Previously, the cursor appeared white in light mode, making it hard to see. Now it dynamically adapts to the theme for better accessibility.
Fixes: #406
Dark mode:
Light mode:
> fix(cursor): correct color in light and dark mode

- Backend/controllers/event.controller.js
added event controller of event creation deletion  and updation 
Fixes: #403 
@Bhavya1352 please also add lable of ssoc and also on pr #414 and #390
> event controller added

- components/map/MapExplorer.js
- components/sections/HeroSection.js
Fixes: #429
- [x ] UI/UX Enhancement 🎨
- [x ] My code follows the contribution guidelines of Eventmappr
@Bhavya1352 pls merge this
> removed duplicate button

- Backend/app.min.js
- Backend/routes/event.routes.js
This PR adds Event API routes to the project. It sets up an eventRouter with all necessary CRUD operations for managing events.
🔧 Implemented Features
POST /api/v1/events/create → Create a new event
GET /api/v1/events/ → Fetch all events
GET /api/v1/events/:id → Fetch a single event by ID
PUT /api/v1/events/update/:id → Update an existing event by ID
DELETE /api/v1/events/delete/:id → Delete an event by ID
📂 Files Modified / Added
routes/event.routes.js → Defined event routes
app.js → Registered event router at /api/v1/events
#447
> event routes created for event controller 
